### DISCUSSION TITLE
Dashboard?

### DISCUSSION THREAD

**Discussion by mnneely** [natekspencer/hacs-pura#56] [Q&A]
Now that there’s a cool integration that controls Pura, has anybody made a nice dashboard to go with it? I’m being lazy, I know, but why reinvent a wheel if done already?

**Comment by natekspencer** [comment]
This is how mine looks, which I've been thinking about making into a dynamic dashboard when I have time:
![Screenshot 2024-05-21 at 07 56 29](https://github.com/natekspencer/hacs-pura/assets/3792831/4aa9605b-5675-4da3-81a2-72c877f65fc3)

**Reply by mnneely** [reply]
Thanks! Would you mind sharing the raw code for your dashboard? BTW, I bought you a beer under my other handle, Journeymnn. :) Thanks again for making this. One of the main reasons I wanted it was because the Pura Away mode doesn’t work very well for me, and now I can use HA to automate that better based on family members absent.

**Reply by natekspencer** [reply]
I saw that, and thank you! Away mode was one of the primary reasons for taking the time to build it out as well. Using a single phone in isolation just isn't great haha. That and timers/schedules. I wanted more granular control based off of what was actually happening in my home.

Here's the code for one of the diffusers, just repeat for each one you need with the appropriate name changes:

```yaml
      - type: vertical-stack
        title: Kitchen
        cards:
          - type: custom:mushroom-chips-card
            chips:
              - type: entity
                entity: sensor.kitchen_diffuser_active_fragrance
              - type: entity
                entity: sensor.kitchen_diffuser_controller
              - type: conditional
                conditions:
                  - condition: state
                    entity: binary_sensor.kitchen_diffuser_connected
                    state_not: 'on'
                chip:
                  type: entity
                  entity: binary_sensor.kitchen_diffuser_connected
          - type: entities
            entities:
              - entity: select.kitchen_diffuser_fragrance
                name: Fragrance
              - entity: number.kitchen_diffuser_intensity
                name: Intensity
              - entity: switch.kitchen_diffuser_away_mode
                name: Away mode
          - type: custom:mushroom-light-card
            entity: light.kitchen_diffuser_nightlight
            name: Nightlight
            fill_container: false
            use_light_color: true
            show_brightness_control: true
            show_color_temp_control: false
            show_color_control: true
            collapsible_controls: false
          - type: entities
            entities:
              - entity: switch.kitchen_diffuser_ambient_mode
                name: Ambient mode
          - type: horizontal-stack
            cards:
              - type: vertical-stack
                cards:
                  - type: custom:mushroom-title-card
                    subtitle: Slot 1
                    alignment: center
                    style: |
                      ha-card {
                        padding-top: 5px !important;
                        padding-bottom: 0px !important;
                        margin-bottom: -5px;
                      }
                  - type: custom:mushroom-entity-card
                    entity: sensor.kitchen_diffuser_slot_1_fragrance
                    primary_info: state
                    secondary_info: none
                  - type: custom:mushroom-entity-card
                    entity: sensor.kitchen_diffuser_slot_1_runtime
                    name: Runtime
                  - type: custom:mushroom-entity-card
                    entity: sensor.kitchen_diffuser_slot_1_installed
                    name: Installed
              - type: vertical-stack
                cards:
                  - type: custom:mushroom-title-card
                    subtitle: Slot 2
                    alignment: center
                    style: |
                      ha-card {
                        padding-top: 5px !important;
                        padding-bottom: 0px !important;
                        margin-bottom: -5px;
                      }
                  - type: custom:mushroom-entity-card
                    entity: sensor.kitchen_diffuser_slot_2_fragrance
                    primary_info: state
                    secondary_info: none
                  - type: custom:mushroom-entity-card
                    entity: sensor.kitchen_diffuser_slot_2_runtime
                    name: Runtime
                  - type: custom:mushroom-entity-card
                    entity: sensor.kitchen_diffuser_slot_2_installed
                    name: Installed
```
