### DISCUSSION TITLE
Away mode automations

### DISCUSSION THREAD

**Discussion by derekcentrico** [natekspencer/hacs-pura#68] [Q&A]
Got Pura integrated - awesome!

I found it super annoying that the away mode has been unreliable in various ways for the app including not being able to have multiple devices (family members) used.

I'd like to use the integration and my HA zones to control away mode, or to disable the Puras when away and enable them when home.

I see an entity on each of my Puras  For example:  switch.basement_diffuser_away_mode.  My device controls the Pura app and I'm home right now.  But, this entity shows ON.  I'm assuming this just controls enabling/disabling the ability to use away mode on the device.

I see sensor.basement_diffuser_controller has "default" for its state.  Not sure what this one does/what states it would have aside from default.

What would be the way to enable/disable the device based upon zone triggers?

**Comment by natekspencer** [comment]
As you've discovered, the `away mode` entity is just whether that particular diffuser has the feature enabled or not.

The `controller` entity is read only and displays what mode is currently controlling the device. So far I've seen: default, schedule, and timer.

The `fragrance` select entity is what you are going to want to use to turn it off. And you can either use the action `pura.start_timer` or the select entity to choose a fragrance you want to start when you are home.

**Comment by derekcentrico** [comment]
Copy, okay so the question now is can I just call select.basement_diffuser_fragrance off when I leave and then either slot_1 or slot_2 when we arrive to just re-enable the normally programmed schedule?  I'm thinking it would be less of a pain if I have morning/afternoon arrival triggers which match the two scents (we do morning/afternoon switching).  Otherwise, my wife has like 7 to 9 schedules per Pura which is likely going to get complicated?  Trying to find the best path here.  Thanks so much.

**Reply by natekspencer** [reply]
Unfortunately schedules do complicate things since they are kind of "dumb". If you turn off the fragrance during a schedule, it essentially disables it until the next time that program is supposed to start. So if you come home in the middle of a scheduled time, you can't turn that particular schedule on and have it run its program.

**Reply by derekcentrico** [reply]
Interesting.  I might not care for it to run when I come home if it's in the middle of a schedule.  Any thoughts on just simple enable/disable so it keeps to whatever the next schedule would be?  Or, is that impossible?  Trying to think how best to use this without getting too complex.

**Reply by natekspencer** [reply]
You could set up an automation that monitors when they turn on. Then, if you're not home and the controller is "schedule", you could turn it off. That's probably the simplest way.

**Reply by derekcentrico** [reply]
So, I came up with this now that I had time to think on it:

```
trigger:
  # Trigger that occurs after everyone departs
  - platform: state
    entity_id: group.familypresence
    to: 'not_home'
    for: '00:05:00'
  # Trigger for Pura's turning on to ensure someone is here
  - platform: state
    entity_id:
      - sensor.family_room_diffuser_controller
      - sensor.basement_diffuser_controller
      - sensor.living_room_diffuser_controller
      - sensor.upstairs_diffuser_controller
    to: 'on'
condition:
  # Ensure that no one is home for second trigger set
  - condition: state
    entity_id: group.familypresence
    state: 'not_home'
action:
  # Turn off all Puras
  - service: homeassistant.turn_off
    target:
      entity_id:
        - sensor.family_room_diffuser_controller
        - sensor.basement_diffuser_controller
        - sensor.living_room_diffuser_controller
        - sensor.upstairs_diffuser_controller
```

Does this make sense?  Most unsure about the action service.

**Reply by natekspencer** [reply]
`homeassistant.turn_off` will disable an integration and is not what you want.

Instead, do something like:
```yaml
action: select.select_option
data:
  option: "off"
target:
  entity_id:
    - select.family_room_diffuser
    - select. basement_diffuser
    - ...etc
```

**Reply by derekcentrico** [reply]
Copy.  Yeah my trigger failed.  I used "on" which isn't an option based on what you said before.  So, I will go with a "from: none" option for the read-only sensor.X_diffuser_controller entities.  Will post the working automation once confirmed.

**Reply by derekcentrico** [reply]
Okay, so I have to use _diffuser_fragrance it seems.

```
trigger:
  - platform: state
    entity_id: group.familypresence
    to: not_home
    for: "00:03:00"
  - platform: state
    entity_id:
      - sensor.family_room_diffuser_active_fragrance
      - sensor.basement_diffuser_active_fragrance
      - sensor.living_room_diffuser_active_fragrance
      - sensor.upstairs_diffuser_active_fragrance
    from: none
condition:
  - condition: state
    entity_id: group.familypresence
    state: not_home
action:
  - data:
      option: "off"
    target:
      entity_id:
        - select.family_room_diffuser_fragrance
        - select.basement_diffuser_fragrance
        - select.living_room_diffuser_fragrance
        - select.upstairs_diffuser_fragrance
    action: select.select_option
```
