### ISSUE TITLE
Automation Best Practices

### ISSUE THREAD

**Issue by lux4rd0** [natekspencer/hacs-pura#21]
### The request

Looking to obtain better automation details for controlling the Puras. A few things I've noticed:

Turning off using the device "Pura Switch" doesn't seem to work. I need to change the "Select Fragrance" to "Off"

```
alias: Loft Pura Off
description: ""
trigger:
  - platform: state
    entity_id:
      - binary_sensor.tyle_2nd_floor_group_motion
    to: "off"
    for:
      hours: 0
      minutes: 20
      seconds: 0
condition: []
action:
  - service: light.turn_off
    data: {}
    target:
      device_id:
        - f8330d0b811b3346772835b955e3376d
    enabled: true
  - service: select.select_option
    data:
      option: "Off"
    target:
      device_id:
        - f8330d0b811b3346772835b955e3376d
mode: single
```

Same thing for turning on. But I must also choose the "Number Set" for the Intensity.

```
alias: Kitchen Pura On
description: ""
trigger:
  - type: motion
    platform: device
    device_id: e282806df8715c1589fbc8075bcf873f
    entity_id: 64af6c043184a1e3d6ddb23cf3b7c2b6
    domain: binary_sensor
condition:
  - condition: state
    entity_id: input_select.mode
    state: Home
action:
  - service: light.turn_on
    data:
      color_name: aqua
      brightness_pct: 100
    target:
      device_id:
        - f5768d206b8fbca08efba0736c39fab8
  - service: select.select_option
    data:
      option: "Slot 2: Volcano"
    target:
      device_id:
        - f5768d206b8fbca08efba0736c39fab8
    enabled: true
  - delay:
      hours: 0
      minutes: 0
      seconds: 5
      milliseconds: 0
  - service: number.set_value
    data:
      value: "4"
    target:
      entity_id:
        - number.kitchen_pura_diffuser_intensity
mode: single

```

Doing so requires a manual field entry for the Scent and the slot. For this example, "Slot 2: Volcano". There's no way to simply  "turn it on" regardless of scent. If I change the scent - I need to update the automation.

For some reason - the "switch.turn_on" service with the Pura device doesn't actually have a "switch" entirety. (Just for Ambient mode and Away mode"

I also need to add a delay when turning on the switches because there's no scent selected when it's turned off (by selecting no scent"), And the automation will fail. Sometimes, it takes longer than 5 seconds (in my example). 

_Can a new service be added to your integration to handle these items? Or a recommended blueprint?_

**New Puras**

Must reload the Device Integration for new Puras to show up.

### Which Pura device(s) is this request for?

- [X] Pura 3
- [X] Pura 4
- [ ] Pura Car
- [X] Other (please specify in the additional information field below)
